#!/usr/bin/env node
// vimrun! node -i -r ./csvchart-node

const fs = require("fs");
const Papa = require("./papaparse.js");

// const argv = process.argv.slice(2);

// var d = fs.readFileSync("test/testfile-01.csv", "utf8");

/* fs.readFile("testfiles/testfile-00.csv", "utf8", (err, data) => {
	if(err) {
		console.error(err);

		return;
	}

	global.csv = Papa.parse(data, {
		dynamicTyping: true,
		skipEmptyLines: true
	}).data;
}); */

fs.readFile("testfiles/testfile-01.csv", "utf8", (err, data) => {
	if(err) {
		console.error(err);

		return;
	}

	var csv = Papa.parse(data, {
		dynamicTyping: true,
		skipEmptyLines: true,
		header: true
	}).data.map(e => [
		e["Search Volume"],
		e["Keyword Difficulty"],
		e["Keyword"]
	]);

	global.csv = [["FOO", "BAR", "BAZ"], ...csv]
});
